Comment out Unit Tests coverage requirements from the pipeline (for the time being)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,15 +59,15 @@ jobs:
         run: dotnet test ${{ env.PATH_TO_ARCH_TESTS }} --configuration ${{ env.BUILD_CONFIGURATION }}
 
       - name: Run Unit Tests with Code Coverage
-        id: unittests
-        continue-on-error: true
+#        id: unittests
+#        continue-on-error: true
         run: |
           dotnet test ${{ env.PATH_TO_UNIT_TESTS }} \
             /p:CollectCoverage=true \
             /p:CoverletOutput="${{ env.REPORT_PATH }}/coverage" \
             /p:CoverletOutputFormat="cobertura" \
-            /p:Threshold=80 \
-            /p:ThresholdType=line \
+#            /p:Threshold=80 \
+#            /p:ThresholdType=line \
             /p:ExcludeByFile="**/AssemblyMarker.cs%2c**/Errors/**/*.cs" \
             --verbosity minimal --results-directory "${{ env.REPORT_PATH }}" \
             --configuration ${{ env.BUILD_CONFIGURATION }}
@@ -90,6 +90,6 @@ jobs:
         run: cat ${{ env.REPORT_PATH }}/generated-report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
         shell: bash
 
-      - name: Fail if tests failed because of low coverage
-        if: steps.unittests.outcome != 'success'
-        run: exit 1
+#      - name: Fail if tests failed because of low coverage
+#        if: steps.unittests.outcome != 'success'
+#        run: exit 1
